spring:
  application:
    name: zoey-music-boot
  profiles:
    active: pro
    include: prodb
#    active: dev
#    include: devdb

logging:
  config: classpath:logback.xml
  level:
    root: info
    cn.sxgan.mapper: debug

# 项目相关配置
zoey:
  # 标题
  doc-title: Zoey Music System API Documentation
  # 所有者信息
  author-name: sxgan
  author-email: sxgan@foxmail.com
  author-url: https://gitee.com/sxgan
  # 版本
  version: 1.0.0
  # 版权年份
  copyright-year: 2024
  # 实例演示开关
  demo-enabled: true
  # 文件路径 示例（ Windows配置D:/zoey/uploadPath，Linux配置 /home/zoey/uploadPath）
  profile: /home/zoey/uploadPath/
  # 获取ip地址开关
  address-enabled: false

# tokenKey
token:
  key: zoey2024