spring:
  application:
    name: zoey-music-admin
  profiles:
    #    active: pro
    #    include: prodb
    active: dev
    include: devdb

logging:
  config: classpath:logback.xml
  level:
    root: info
    cn.sxgan.mapper: debug
# PageHelper 分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countsql
# 项目相关配置
zoey:
  # 标题
  doc-title: Zoey Music System API Documentation
  # 所有者信息
  author-name: sxgan
  author-email: sxgan@foxmail.com
  author-url: https://gitee.com/sxgan
  # 版本
  version: 1.0.0
  # 版权年份
  copyright-year: 2024
  # 实例演示开关
  demo-enabled: true
  # 文件路径 示例（ Windows配置D:/zoey/uploadPath，Linux配置 /home/zoey/uploadPath）
  profile: /home/zoey/uploadPath/
  # 获取ip地址开关
  address-enabled: false

# tokenKey
token:
  key: zoey2024

dubbo:
  scan:
    base-packages: cn.sxgan.admin.service.impl
  registry:
    address: zookeeper://192.168.0.200:2181
  protocol:
    name: dubbo
    port: 22223
  # 暂时关闭，以免端口冲突
  application:
    qos-enable: false